version: '3.7'

services:
  nutanix_thq_exporter:
    build: ./exporters
    container_name: nutanix_thq_exporter
    env_file: .env
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nutanix_thq_exporter
